#' Create a worker object for use as a worker with master objects generated by [LinearregressionMaster()]
#' @description `LinearRegressionWorker` objects are worker objects at each site of
#' a distributed univariate linear model computation
#'
#' @docType class
#' @seealso `LinearRegressionMaster` which goes hand-in-hand with this object
#' @importFrom R6 R6Class
#' @section Methods:
#' \describe{
#'   \item{`LinearRegressionWorker$new(defn, data, stateful=TRUE)`}{Create a new LinearRegressionWorker instance
#'         object using formula and data. The stateful flag indicates whether the object
#'         state is to be saved between iterations}
#'   \item{`sumRSS(beta, ...)`}{Compute the sum of the squared residuals for the input parameter beta (vector length two). 
#'         The return value is a named list with one component: `rss2` contains the sum of the squared residuals.}
#'   \item{`kosher()`}{Check if inputs and state of object are sane. For future use}
#'   \item{`getP()`}{Returns the dimension of the parameter `vector`}
#'   \item{`getStateful()`}{Returns `TRUE` if object is stateful, else `FALSE`}
#' }
#'
#' @export
#' @format An [R6::R6Class()] generator object
LinearRegressionWorker <- R6Class(
    "LinearRegressionWorker",
    private = list(
        defn = NA # should I include a loss function in the defintiion to do local optimization on the worker side?
      , stateful = TRUE
      , rs = NA
      , p = NA
      , data = NULL
      , result = list()
    ),
    public = list(
        initialize = function(defn, data, stateful=TRUE) {
            private$defn <- defn
            private$stateful <- stateful
            private$data <- data
            stopifnot(self$kosher())
        } , getP = function(...) {
            private$p
        },  getStateful = function() {
            private$stateful
        }, sumRSS = function(beta, ...) {
          # sum of the squared residuals given beta 0 (intercept) and beta 1 (slope)
            sum((beta[1] + beta[2] * data$x - data$y)^2) 
        }, kosher = function() {
            ## add sanity checks
            TRUE
        })
)

#' Create a master object to control worker objects generated by [LinearRegressionWorker()]
#' @description `LinearRegressionMaster` objects instantiate and run a distributed Cox model
#' computation fit
#' @docType class
#' @seealso `LinearRegressionWorker` which generates objects matched to such a master object
#' @importFrom R6 R6Class
#' @section Methods:
#'
#' \describe{
#'   \item{`LinearRegressionMaster$new(defn, data, debug=FALSE)`}{Create a new
#'         LinearRegressionMaster object using the defn and data. The debug flag is useful for
#'         debugging}
#'   \item{`logLik(beta, ...)`}{Compute the partial log likelihood for all the data
#'         by aggregating the values at each site. The return value is numeric scalar with
#'         two attributes: `gradient` contains the score vector, and `hessian`
#'         contains the estimated hessian matrix}
#'   \item{`sumRSS(beta0, beta1, ...)`}{Compute the sum of the squared residuals for all the data
#'         by aggregating the values at each site. The return value is numeric scalar which is the sum of the squared residuals across all sites.}
#'   \item{`addSite(name, url = NULL, worker = NULL)`}{Add a worker
#'         site for participating in the distributed computation. Exactly one of `url` or `worker` should be specified}
#'   \item{`var(beta, ...)`}{Compute the variance of the parameter vector beta}
#'   \item{`kosher()`}{Check if inputs and state of object are sane. For future use}
#'   \item{`getP()`}{Returns the dimension of the parameter vector}
#'   \item{`run(control)`}{Run the fitting iterations and save the result using control object}
#'   \item{`summary()`}{Return a summary data frame columns for `coef`, `exp(coef)`,
#'         standard error, z-score, and p-value for each parameter in the model following
#'         the same format as the `survival` package}
#' }
#'
#' @export
#' @format An [R6::R6Class()] generator object
LinearRegressionMaster <- R6Class(
    "LinearRegressionMaster",
    private = list(
        defn = NA
        , dry_run = FALSE,
        sites = list()
        , p = NA
      , mapFn = function(site, beta) {
          payload <- list(objectId = site$instanceId,
                          method = "sumRSS",
                          beta = beta)
          q <- POST(.makeOpencpuURL(urlPrefix=site$url, fn="executeMethod"),
                    body = toJSON(payload),
                    add_headers("Content-Type" = "application/json"),
                    config=getConfig()$sslConfig
                    )
          ## Should really examine result here.
          .deSerialize(q)
      }, result = list()
       , debug = FALSE
    ),
    public = list(
        initialize = function(defn, debug = FALSE) {
            'Initialize the object with a defn and flag'
            private$defn <- defn
            private$debug <- debug
            stopifnot(self$kosher())
        }, kosher = function() {
            ' Check for sanity'
            TRUE
        }, sumRSS = function(beta) {
            'Compute the sum of squared residuals on all of the data'
            debug <- private$debug
            if (debug) {
                print("beta")
                print(beta)
            }
            sites <- private$sites
            n <- length(sites)
            if (private$dry_run) {
                mapFn <- function(x, arg) x$worker$sumRSS(arg)
            } else {
                mapFn <- private$mapFn
            }
            results <- Map(mapFn, sites, rep(list(beta), n))
            value <- Reduce(f = sum, results)
            if (debug) {
                print("value")
                print(value)
            }
            value # returns the sum of the residual sum of squares for all sites
        }, addSite = function(name, url = NULL, worker = NULL) {
            'Add a site identified by url with a name'
            ## critical section start
            ## This is the time to cache "p" and check it
            ## against all added sites
            ## Only one of url/worker should be non-null
            stopifnot(is.null(url) || is.null(worker))
            n <- length(private$sites)
            if (is.null(url)) {
                private$dry_run <- private$dry_run || TRUE
                private$sites[[n+1]] <- list(name = name, worker = worker)
            } else {
                localhost <- (grepl("^http://localhost", url) ||
                              grepl("^http://127.0.0.1", url))
                private$sites[[n+1]] <- list(name = name, url = url,
                                             localhost = localhost,
                                             dataFileName = if (localhost) paste0(name, ".rds") else NULL)
            }
            ## critical section end
            ## TODO: figure out how the master is running the workers asynchronously.
        }, run = function(control=NULL) {
            'Run estimation'
            dry_run <- private$dry_run
            debug <- private$debug
            defn <- private$defn
            if (debug) {
                print("run(): checking worker object creation")
            }
            if (dry_run) {
                ## Workers have already been created and passed
                sites <- private$sites
                pVals <- sapply(sites, function(x) x$worker$getP())
            } else {
                ## Create an instance Id
                instanceId <- generateId(object=list(Sys.time(), self))
                ## Augment each site with object instance ids
                private$sites <- sites <-
                    lapply(private$sites,
                           function(x) list(name = x$name,
                                            url = x$url,
                                            localhost = x$localhost,
                                            dataFileName = x$dataFileName,
                                            instanceId = if (x$localhost) x$name else instanceId))
                ## Create instance objects
                sitesOK <- sapply(
                    sites,
                    function(x) {
                        payload <- if (is.null(x$dataFileName)) {
                                       list(defnId = defn$id, instanceId = x$instanceId)
                                   } else {
                                       list(defnId = defn$id, instanceId = x$instanceId,
                                            dataFileName = x$dataFileName)
                                   }
                        q <- POST(url = .makeOpencpuURL(urlPrefix=x$url, fn="createInstanceObject"),
                                  body = toJSON(payload),
                                  add_headers("Content-Type" = "application/json"),
                                  config=getConfig()$sslConfig
                                  )
                        .deSerialize(q)
                    })

                ## I am not checking the value of p here; I do it later below
                if (!all(sitesOK)) {
                    warning("run():  Some sites did not respond successfully!")
                    private$sites <- sites <- sites[which(sitesOK)]  ## Only use sites that created objects successfully.
                }
                ## stop if no sites
                if (debug) {
                    print("run(): checking p")
                }
                pVals <- sapply(
                    sites,
                    function(x) {
                        payload <- list(objectId = x$instanceId, method = "getP")
                        q <- POST(.makeOpencpuURL(urlPrefix=x$url, fn="executeMethod"),
                                  body = toJSON(payload),
                                  add_headers("Content-Type" = "application/json"),
                                  config=getConfig()$sslConfig
                                  )
                        .deSerialize(q)
                    })
            }
            if (debug) {
                print(pVals)
            }
            if (any(pVals != pVals[1])) {
                stop("run(): Heterogeneous sites! Stopping!")
            }
            p <- pVals[1]
            if (debug) {
                print(paste("p is ", p))
            }

            ## TODO: solve for the RSS from each site
            control <- list(iter.max=1000, eps=0)
            prevBeta <- beta <- rep(0, p) # define the first set of betas to use
            m <- prevRSS <- self$sumRSS(beta) # initial loss using first betas
            # iter <- 0
            # returnCode <- 0
            ### Iterating here to find final betas
            # repeat {
            #   # 
            #     beta <- beta - solve(attr(m, "hessian")) %*% attr(m, "gradient")
            #     iter <- iter + 1
            #     m <- self$sumRSS(beta) # get the RSS from each site
            #     if (m - prevRSS <= control$eps) {
            #         break
            #     }
            #   ###
            #     if (iter >= control$iter.max) {
            #         returnCode <- 1
            #         break
            #     }
            #     prevBeta <- beta
            #     prevRSS <- m
            #     if (debug) {
            #         print(beta)
            #     }
            # }
            
            fit <- optim(prevBeta
                         , fn = self$sumRSS
                         , hessian = TRUE)
            
            # saving the result
            private$result <- result <- list(beta = fit$par
                                             , iter = fit$counts
                                             , hessian = fit$hessian
                                             , returnCode = fit$convergence)

            if (!dry_run) {
                if (debug) {
                    print("run(): checking worker object cleanup")
                }
                sitesOK <- sapply(
                    sites,
                    function(x) {
                        payload <- list(instanceId = x$instanceId)
                        q <- POST(url = .makeOpencpuURL(urlPrefix=x$url, fn="destroyInstanceObject"),
                                  body = toJSON(payload),
                                  add_headers("Content-Type" = "application/json"),
                                  config=getConfig()$sslConfig
                                  )
                        .deSerialize(q)
                    })
                if (!all(sitesOK)) {
                    warning("run():  Some sites did not clean up successfully!")
                }
            }
            ## Should probably clean up sites list and remove instanceId too...
            result
        },
        summary = function() {
            'Run the summary'
            result <- private$result
            if (length(result) == 0) {
                warning("Calculating...")
                run()
                result <- private$result
            }

            d <- as.data.frame(t(sapply(seq.int(length(result$beta)),
                                        function(i) {
                                            coef <- result$beta[i]
                                            eCoef <- exp(coef)
                                            se <- sqrt(result$var[i, i])
                                            z <- coef / se
                                            pValue <- 2*pnorm(z, lower.tail=(z <= 0))
                                            c("coef"=coef, "exp(coef)"=eCoef, "se(coef)"=se, z=z, p=pValue)
                                        })))
            d
        }
    )
)


